FROM node:22-alpine

RUN apk add --no-cache python3 make g++ libc6-compat

WORKDIR /app

# Só package.json pra instalar deps
COPY package.json package-lock.json ./

RUN npm ci



# Porta que o Nest usa
EXPOSE 3000

# Comando de dev com watch
CMD ["npm", "run", "start:dev"]
