FROM node:22-alpine

RUN apk add --no-cache python3 make g++ libc6-compat

WORKDIR /app


COPY package.json package-lock.json ./

RUN npm ci

COPY . .

# Porta que o Nest usa
EXPOSE 3000

# Comando de dev com watch
CMD ["npm", "run", "start:dev"]
