# 1. Imagem base
FROM node:22-alpine

# 1. Ferramentas de build pra dependências nativas (argon2 etc)
RUN apk add --no-cache python3 make g++ libc6-compat


# 3. Diretório de trabalho
WORKDIR /app

# copia package.json + package-lock.json
COPY package.json package-lock.json ./

RUN npm ci

# 6. Copia o restante do código
COPY . .

# 7. Build da aplicação (se você já estiver usando o build do Nest)
RUN npm run build

# 8. Porta exposta
EXPOSE 3000

# 9. Comando padrão (produção)
CMD ["npm","run", "start:prod"]
