services: 
  mongo: 
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports: 
      - "27017:27017"
    volumes: 
      - mongo_data:/data/db 

  rabbitmq: 
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"    # broker
      - "15672:15672"  # painel web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest


  weather-api: 
    build:
      context: ./wather-api
      dockerfile: Dockerfile
    container_name: weather-api
    restart: unless-stopped
    env_file:
      - ./wather-api/.env
    ports: 
      - "3000:3000"
    environment:
      MONGO_URI_DEV: mongodb://mongo:27017/gdash
      NODE_ENV: production
      PORT: "3000"
    depends_on:
      - mongo

  go-worker: 
    build:
      context: ./go-worker
      dockerfile: Dockerfile
    container_name: go-worker
    restart: unless-stopped
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      NEST_API_URL: http://weather-api:3000/api/weather/intake
    depends_on:
      - rabbitmq
      - weather-api

  data-collector:
    build:
      context: ./data-colector  # também confere esse nome de pasta
      dockerfile: Dockerfile
    container_name: data-collector
    restart: unless-stopped
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      INPUT_QUEUE: weather.locations
      OUTPUT_QUEUE: weather.jobs
    depends_on:
      - rabbitmq



volumes:
  mongo_data:
