FROM python:3.12-slim

WORKDIR /app

# Copia só requirements pra cache
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copia o código
COPY . .

# Exemplo de entrypoint
CMD ["python", "main.py"]
