root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/worker ."
  entrypoint = "./tmp/worker"
  include_ext = ["go"]
  exclude_dir = ["vendor", "tmp", ".git"]
  exclude_file = []
  delay = 1000

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true