FROM golang:1.23-alpine AS builder

WORKDIR /app

# Copia arquivos de módulo primeiro
COPY go.mod go.sum ./
RUN go mod download

# Copia o resto do código
COPY . .

# Compila o binário
RUN go build -o worker ./cmd/worker

# Imagem final, leve
FROM alpine:3.20

WORKDIR /app

COPY --from=builder /app/worker .

CMD ["./worker"]
